name: Build
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/setup-node@v1
              with:
                node-version: 10.x
            - uses: actions/checkout@v2
            - uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '3.1.1'
            - run: dotnet build